const { assert } = require('../util')

const LinkedList = require('./linked_list')

var linkedList = new LinkedList()

linkedList.add('A')
linkedList.add('B')
linkedList.add('C')
assert(linkedList.getSize() == 3, 'list size test ')
assert(linkedList.tail.val == 'C', 'list tail test 1 ')
linkedList.removeTail()
assert(linkedList.tail.val == 'B', 'list tail test 2 ')
linkedList.prepend('0')
assert(linkedList.head.val == '0', 'list head test 1 ')
linkedList.add('D')
linkedList.add('E')
console.log(linkedList.toString())
linkedList.remove('B')
assert(linkedList.getSize() == 4, 'list remove and size test 1 ')
assert(linkedList.find(el => el == 'B') == null, 'list remove test ')
linkedList.reverse()
assert(linkedList.head.val == 'E' && linkedList.tail.val == '0', 'list reverse test ')
console.log(linkedList.toString())