const { assert } = require('../util')

const DoublyLinkedList = require('./doubly_linked_list')

var doublyLinkedList = new DoublyLinkedList()

doublyLinkedList.add('A')
doublyLinkedList.add('B')
doublyLinkedList.add('C')
assert(doublyLinkedList.getSize() == 3, 'list size test ')
assert(doublyLinkedList.tail.val == 'C', 'list tail test 1 ')
doublyLinkedList.removeTail()
assert(doublyLinkedList.tail.val == 'B', 'list tail test 2 ')
doublyLinkedList.prepend('0')
assert(doublyLinkedList.head.val == '0', 'list head test 1 ')
doublyLinkedList.add('D')
doublyLinkedList.add('E')
console.log(doublyLinkedList.toString())
doublyLinkedList.remove('B')
assert(doublyLinkedList.getSize() == 4, 'list remove and size test 1 ')
assert(doublyLinkedList.find('B') == null, 'list remove test ')
doublyLinkedList.reverse()
assert(doublyLinkedList.head.val == 'E' && doublyLinkedList.tail.val == '0', 'list reverse test ')
console.log(doublyLinkedList.toString())